### PR TITLE
Update the precommit config

### PR DESCRIPTION
**Pull request by brian-rose**
This PR might help resolve a pre-commit conflict found in #67.

isort gets updated to its latest version, and the obsolete `seed-isort-config` is removed.

### CODE REVIEW

**Comment by brian-rose** [comment]
The CI will probably fail here, since we're waiting on the fix in #67. But pre-commit.ci is happy so we should probably merge this.

**Review by mgrover1 — APPROVED** [review]
This fixes the issue with the pre-commit file, once we merge this, I can pull that into the other PR fixing the environment.

**Comment by mgrover1** [comment]
@brian-rose should we go ahead and merge? I know that the CI will fail until we merge with #67

**Comment by brian-rose** [comment]
> @brian-rose should we go ahead and merge? I know that the CI will fail until we merge with #67

Yes, I'll pull the trigger.

**Pull request merged**
