### PR TITLE
FIX: Fix the mamba-forge failing CI

### PR DESCRIPTION
**Pull request by mgrover1**
This fixes our mamba forge configuration which should resolve the failing CI.

### CODE REVIEW

**Comment by brian-rose** [comment]
Not clear to me why pre-commit is failing here, but the error message looks similar to something from https://github.com/ProjectPythia/projectpythia.github.io/pull/307

**Comment by brian-rose** [comment]
I'll attempt to update the `.pre-commit-config.yaml` in a separate PR

**Comment by mgrover1** [comment]
@brian-rose pre-commit is passing!! Now to just wait for the CI to finish...

**Comment by brian-rose** [comment]
> @brian-rose pre-commit is passing!! Now to just wait for the CI to finish...

and since it's now mambaforge, it doesn't take nearly as long!

**Review by brian-rose — APPROVED** [review]

**Pull request merged**
